#pragma once

typedef unsigned int ITL_ERT;

#define ITL_ERT_SUCCESS 0

#define ITL_ERT_GET(E1) (E1&0xffff)
#define ITL_ERT_IS_EQUAL(e1,e2) ( (e1 & 0xffff ) == (e2 & 0xffff) )

#define ITL_ERT_CODE(err) (__LINE__ << 16 | err)
#define ITL_ERT_FAIL    ITL_ERT_CODE(1)
#define ITL_ERT_INVALUD_PARS    ITL_ERT_CODE(2)
#define ITL_ERT_INSTANCE_HEIF_FAIL   ITL_ERT_CODE(3)
#define ITL_ERT_GET_METABOX_FAIL  ITL_ERT_CODE(4)
#define ITL_ERT_NO_IMAGE_DATA       ITL_ERT_CODE(5)
#define ITL_ERT_NEW_MEMORY_FAIL       ITL_ERT_CODE(6)
#define ITL_ERT_INIT_CODEC_FAIL     ITL_ERT_CODE(7)
#define ITL_ERT_AVCODEC_SEND_PACKET_FAIL     ITL_ERT_CODE(8)
#define ITL_ERT_RECEIVE_FRAME_FAIL    ITL_ERT_CODE(9)
#define ITL_ERT_STITCH_IMAGE_FAIL     ITL_ERT_CODE(0x0a)
#define ITL_ERT_GET_DECODERPARA_FAIL  ITL_ERT_CODE(0x0b)
#define ITL_ERT_WRITE_INMAGE_FAIL  ITL_ERT_CODE(0x0c)
#define ITL_ERT_GETINFO_FAIL  ITL_ERT_CODE(0x0d)
#define ITL_ERT_NO_THUMBNAIL_DATA       ITL_ERT_CODE(0x0e)
